name: Release

on:
  workflow_dispatch:
  # push:
  #   tags:
  #   - "v*"

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Push Docker
      run: (echo '${{ secrets.REGISTRY_PASSWORD }}' | docker login --username '${{ secrets.REGISTRY_USER }}' --password-stdin reg0.dreamlab.net) && make push

    - uses: "marvinpinto/action-automatic-releases@latest"
      with:
        repo_token: "${{ secrets.GITHUB_TOKEN }}"
        prerelease: false
